feat(edge): support edge stacks for standalone
portainer/agent pull request #175
Opened 2021-02-17 09:45 UTC by chiptus

fix [CE-208]

2021-02-23 22:38 UTC, deviantony requested changes
Trying to deploy this agent using the following command and I get the following error in the logs (agent can't start):

```
docker run -d -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker/volumes:/var/lib/docker/volumes -v /:/host -v portainer_agent_data:/data --restart always -e EDGE=1 -e EDGE_ID=3a2d806e-98de-4b01-9ac0-a3c69f88615e -e EDGE_KEY=[REDACTED] -e CAP_HOST_MANAGEMENT=1 --name portainer_edge_agent portainerci/agent:edge-compose-stacks
```

```
docker logs -f portainer_edge_agent
2021/02/23 22:36:27 [WARN] [os,options] [message: the CAP_HOST_MANAGEMENT environment variable is deprecated and will likely be removed in a future version of Portainer agent]
2021/02/23 22:36:27 [INFO] [main] [message: Agent running on Docker platform]
2021/02/23 22:36:27 [INFO] [main,edge] [message: Edge key loaded from options]
2021/02/23 22:36:27 [ERROR] [main,edge] [message: Unable to start Edge manager] [error: docker-compose binary not found]
2021/02/23 22:36:27 [WARN] [os,options] [message: the CAP_HOST_MANAGEMENT environment variable is deprecated and will likely be removed in a future version of Portainer agent]
2021/02/23 22:36:27 [INFO] [main] [message: Agent running on Docker platform]
2021/02/23 22:36:27 [INFO] [main,edge] [message: Edge key loaded from options]
2021/02/23 22:36:27 [ERROR] [main,edge] [message: Unable to start Edge manager] [error: docker-compose binary not found]
2021/02/23 22:36:28 [WARN] [os,options] [message: the CAP_HOST_MANAGEMENT environment variable is deprecated and will likely be removed in a future version of Portainer agent]
2021/02/23 22:36:28 [INFO] [main] [message: Agent running on Docker platform]
2021/02/23 22:36:28 [INFO] [main,edge] [message: Edge key loaded from options]
2021/02/23 22:36:28 [ERROR] [main,edge] [message: Unable to start Edge manager] [error: docker-compose binary not found]
2021/02/23 22:36:29 [WARN] [os,options] [message: the CAP_HOST_MANAGEMENT environment variable is deprecated and will likely be removed in a future version of Portainer agent]
2021/02/23 22:36:29 [INFO] [main] [message: Agent running on Docker platform]
2021/02/23 22:36:29 [INFO] [main,edge] [message: Edge key loaded from options]
2021/02/23 22:36:29 [ERROR] [main,edge] [message: Unable to start Edge manager] [error: docker-compose binary not found]
2021/02/23 22:36:30 [WARN] [os,options] [message: the CAP_HOST_MANAGEMENT environment variable is deprecated and will likely be removed in a future version of Portainer agent]
2021/02/23 22:36:30 [INFO] [main] [message: Agent running on Docker platform]
2021/02/23 22:36:30 [INFO] [main,edge] [message: Edge key loaded from options]
2021/02/23 22:36:30 [ERROR] [main,edge] [message: Unable to start Edge manager] [error: docker-compose binary not found]

```

2021-04-11 23:44 UTC, deviantony approved these changes
LGTM

2021-04-12 23:57 UTC, sbusso approved these changes

2021-06-14 19:45 UTC, sbusso approved these changes

2021-07-07 21:26 UTC, sbusso approved these changes

2021-07-08 23:50 UTC, itsconquest approved these changes
LGTM!

2021-07-08 23:50 UTC, merged