Add support for running the agent with podman as container management…
portainer/agent pull request #179
Opened 2021-03-12 11:28 UTC by Subaro

… system

2021-03-15 23:43 UTC, deviantony commented
Thanks a lot for the contribution @Subaro ! Ask stated in https://github.com/portainer/portainer/issues/2991 we'll discuss this one internally and I'll keep you posted.

2021-03-16 14:10 UTC, JBartscher commented on cmd/agent/main.go
> +				log.Printf("[WARN] [main,docker] [message: Unable to retrieve local agent IP address] [error: %s]", err)
```suggestion
				log.Printf("[WARN] [main,podman] [message: Unable to retrieve local agent IP address, using '%s' instead] [error: %s]",options.AgentServerAddr, err)
```

2021-04-18 22:54 UTC, deviantony commented
Thanks again @Subaro and @JBartscher for your participation on this topic, we're going to review it soon and decide whether we should merge it.

2021-04-22 22:54 UTC, deviantony requested changes
Hi @Subaro,

First of all, thanks a lot for the interest and contribution ! We've had a look at it and we're keen to merge it but we'd like to bring a small change to the deployment UX:

- [ ] We'd like to be consistent with our other CLI options and as such replace the `-e PODMAN_MODE="true"` with `-e PODMAN=1` to start the agent on a Podman environment.

From the usability perspective these are all the changes we need, after this is done, I'll ask our developers to have a look at the implementation.

Thanks again!

2021-04-23 06:32 UTC, Subaro commented
Hello @deviantony,
thank you for your Feedback. I changed the option from `PODMAN_MODE`  to `PODMAN`.

2021-04-23 21:01 UTC, deviantony commented
@Subaro awesome, I'll ask our devs to have a look at the code next.

2021-04-27 00:51 UTC, sbusso approved these changes
LGTM, thanks @Subaro

2021-06-15 03:35 UTC, itsconquest approved these changes
LGTM! great work @Subaro  🎉

2021-06-15 03:35 UTC, merged

2021-06-15 03:41 UTC, deviantony commented
Thanks @Subaro 👍