fix(dockerhub): dockerhub ratelimit issues EE-1032
portainer/agent pull request #197
Opened 2021-07-20 23:56 UTC by hookenz

Stops confusing messages inside the browser debug window.

2021-07-21 22:13 UTC, zees-dev commented
EE does not return error early if there are issues with rate limit responses:
https://github.com/portainer/portainer-ee/blob/f0a1bd7b036054cb560fa6414d02c8900d1c54fb/api/http/handler/endpoints/endpoint_dockerhub_status.go#L137

You may want to do the same here?

2021-07-21 22:21 UTC, zees-dev commented on http/handler/dockerhub/dockerhub_status.go
>  	}
Could just be:
```go
rateLimit, _ := parseNumericHeader(resp.Header, "RateLimit-Limit")
rateLimitRemaining, _ := parseNumericHeader(resp.Header, "RateLimit-Remaining")
```

2021-07-21 22:25 UTC, zees-dev requested changes
Would prefer suggested change to retain parity/familiarity with EE.

2021-07-22 00:04 UTC, zees-dev approved these changes
Discussed on chat; LGTM 👍

2021-07-22 23:19 UTC, sbusso approved these changes

2021-07-26 22:42 UTC, merged