Fix Ratelimit issue with dockerhub
portainer/agent pull request #198
Opened 2021-07-21 04:33 UTC by hookenz

Fixes [EE-1032](https://portainer.atlassian.net/browse/EE-1032)

2021-07-21 22:13 UTC, zees-dev commented
Same response may apply here: https://github.com/portainer/agent/pull/197#issuecomment-884533393

2021-07-21 22:24 UTC, zees-dev requested changes
Would prefer suggested change to retain parity/familiarity with EE.

2021-07-22 00:05 UTC, zees-dev approved these changes
Discussed on chat; LGTM (EE/CE require fix instead) 👍

2021-07-22 23:19 UTC, sbusso approved these changes

2021-07-26 22:41 UTC, merged