feat(edge): add mTLS support
portainer/agent pull request #261
Opened 2022-03-01 22:03 UTC by cheloRydel

2022-03-03 05:24 UTC, chiptus approved these changes
LGTM

btw, what about adding to the main `./dev.sh` something like `./dev.sh ssl` to generate the certs?

2022-03-03 05:24 UTC, chiptus commented on dev-scripts/mtlscerts.sh
> +export CERTDIR=~/.config/portainer/certs/
maybe recieve that as a parameter? 
```suggestion
export CERTDIR=${1:-"~/.config/portainer/certs/"}
```

2022-03-03 15:27 UTC, cheloRydel commented
> 

I'd say to keep those separate, while testing I wanted to be able to generate the certs without having to start the portainer server as well

2022-03-03 15:28 UTC, chiptus commented
> > 
> 
> I'd say to keep those separate, while testing I wanted to be able to generate the certs without having to start the portainer server as well

./dev.sh doesn't start anything, it's just help utiltiles (deploy/compile)...

2022-03-03 15:34 UTC, cheloRydel commented
> > > 
> > 
> > 
> > I'd say to keep those separate, while testing I wanted to be able to generate the certs without having to start the portainer server as well
> 
> ./dev.sh doesn't start anything, it's just help utiltiles (deploy/compile)...

my bad, I was look at the portainer script, not the agent

2022-03-03 19:30 UTC, andres-portainer commented on http/server.go
>  		CipherSuites: []uint16{
The CipherSuites should be removed for TLS 1.3, they are not configurable.

2022-03-03 19:32 UTC, andres-portainer commented on dev-scripts/mtlscerts.sh
> +export HOST=portainer.p1.alho.st
Maybe take this as an argument for the script?

2022-03-03 19:49 UTC, andres-portainer approved these changes

2022-03-06 10:47 UTC, chiptus commented on dev.sh
> +    mtlscerts)
since mtlscerts expose a script and not a function, this will run it anyway (on any run of `./dev.sh`).

I'd say, remove this from dev.sh

2022-03-06 10:47 UTC, chiptus requested changes
remove mtls from dev script

2022-03-07 14:01 UTC, chiptus commented on dev-scripts/mtlscerts.sh
> +  export CERTDIR=~/.config/portainer/certs/
these should be `local`, as you don't need them outside of this script
```suggestion
  local CURRENT=$(pwd)
  local HOST=${1:-"portainer.p1.alho.st"}
  local CERTDIR=~/.config/portainer/certs/
```

and also convention says to name local variables with lower caps, but it's not as important

2022-03-07 14:39 UTC, chiptus approved these changes

2022-03-07 19:12 UTC, deviantony approved these changes
LGTM

2022-04-07 14:31 UTC, merged